/*
 * Senso-Care
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"github.com/Senso-Care/SensoApi/internal/models"
	"net/http"
)



// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface {
	GetLastMetrics(http.ResponseWriter, *http.Request)
	GetMetrics(http.ResponseWriter, *http.Request)
	GetMetricsFromSensor(http.ResponseWriter, *http.Request)
	GetMetricsFromType(http.ResponseWriter, *http.Request)
	GetSensors(http.ResponseWriter, *http.Request)
	PostMetricsFromType(http.ResponseWriter, *http.Request)
}


// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultApiServicer interface {
	GetLastMetrics(context.Context, string, string) (ImplResponse, error)
	GetMetrics(context.Context, string) (ImplResponse, error)
	GetMetricsFromSensor(context.Context, string, string) (ImplResponse, error)
	GetMetricsFromType(context.Context, string, string) (ImplResponse, error)
	GetSensors(context.Context, string) (ImplResponse, error)
	PostMetricsFromType(context.Context, string, models.DataPoint) (ImplResponse, error)
}
