version: "3"

services:
  sensoapi:
    image: registry.zouzland.com/sensocare/sensoapi:alpine
    container_name: sensoapi
    restart: always
    expose:
    - 8080
    environment:
      SENSO_CARE_DATABASE_CONNECTIONURI: http://influxdb:8086
      SENSO_CARE_DATABASE_USERNAME: admin
      SENSO_CARE_DATABASE_PASSWORD: admin
      SENSO_CARE_DATABASE_DBNAME: sensocare
      SENSO_CARE_MOCK: "false"
  nginx-proxy:
    restart: always
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - "${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro"